src/objects/Bill__c.object
<CustomObject>
    <fields>
        <fullName>Bill_Owner__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Bill Owner</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Bills</relationshipLabel>
        <relationshipName>Bills</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Loan_Holder__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Loan Holder</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Bills</relationshipLabel>
        <relationshipName>Bills</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Pay_Date__c</fullName>
        <label>Pay Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Payed_Date__c</fullName>
        <label>Payed Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Bill_Status</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Bill_Type</valueSetName>
        </valueSet>
    </fields>
    <label>Bill</label>
    <nameField>
        <label>Bill Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bills</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>IsLoggedOn__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsLoggedOn</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Key__c</fullName>
        <label>Key</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/globalValueSets/Bill_Status.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Do zapłaty</fullName>
        <default>true</default>
        <label>Do zapłaty</label>
    </customValue>
    <customValue>
        <fullName>Zapłacone</fullName>
    </customValue>
    <customValue>
        <fullName>Do wyjaśnienia</fullName>
    </customValue>
    <customValue>
        <fullName>Do potwierdzenia</fullName>
    </customValue>
    <customValue>
        <fullName>Inne</fullName>
    </customValue>
    <masterLabel>Bill Status</masterLabel>
</GlobalValueSet>

src/globalValueSets/Bill_Type.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Kredyt</fullName>
        <default>true</default>
        <label>Kredyt</label>
    </customValue>
    <customValue>
        <fullName>Czynsz</fullName>
    </customValue>
    <customValue>
        <fullName>Gaz</fullName>
    </customValue>
    <customValue>
        <fullName>Prąd</fullName>
    </customValue>
    <customValue>
        <fullName>Woda</fullName>
    </customValue>
    <customValue>
        <fullName>Zakupy</fullName>
    </customValue>
    <customValue>
        <fullName>Inne</fullName>
    </customValue>
    <masterLabel>Bill Type</masterLabel>
</GlobalValueSet>

src/classes/BillsHelper.cls
/**
 * Created by Craftware on 2017-10-06.
 */

public with sharing class BillsHelper {

    /**
     * Generates GUID string key (len=5).
     *
     * @return
     */
    public static String generateKey() {
        Blob b = Crypto.GenerateAESKey(128);
        String h = EncodingUtil.ConvertTohex(b);
        String guid = h.SubString(0, 5);
        return guid;
    }

    /**
     * Find contact by email or return null.
     *
     * @param email (String)
     *
     * @return Contact or null
     */
    public static Contact findContactByEmail(String email) {
        Contact[] contact = [SELECT Id, Email, Name, Key__c, IsLoggedOn__c FROM Contact WHERE Email = :email];
        if (contact.size() > 0) {
            if (contact.size() > 1) {
                return null;
            }
            return contact[0];
        }
        return null;
    }

    /**
     * Return list of all bills
     *
     * @return List of Bills objects
     */
    public static List<Bill__c> getAllBills() {
        return runGenericQuery(null, null);
    }

    /**
     * Returns all bills for selected day.
     *
     * @param day (String) correct format if dd/MM/yyyy
     *
     * @return List of Bills objects
     */
    public static List<Bill__c> getBillsByDay(String day) {
        List<Bill__c> bills = new List<Bill__c>();
        bills = runGenericQuery('Pay_Date__c', String.valueOf(formatDate(day)));
        return bills;
    }

    /**
     * Returns one bill object that match Id
     *
     * @param id (String) id of object
     *
     * @return Bill object
     */
    public static Bill__c getBillById(String id) {
        return runGenericQuery('Id', id)[0];
    }

    /**
     * Performs a generic query on Bill object.
     *
     * @param field (String) field name from Bill object ex. Name, Id.
     * @param value (String) value to include in WHERE clause
     *
     * @return List of Bill objects
     */
    public static List<Bill__c> runGenericQuery(String field, String value) {
        String q = 'SELECT Bill_Owner__c, Id, Loan_Holder__c, Loan_Holder__r.Name, Name, OwnerId, Pay_Date__c, Payed_Date__c, Price__c, Status__c, Title__c, Type__c FROM Bill__c';
        if (!String.isEmpty(field)) {
            if (field.equals('Pay_Date__c')) {
                Date d = Date.valueOf(value);
                q = q + ' WHERE ' + field + ' = :d';
            } else {
                q = q + ' WHERE ' + field + ' = :value';
            }
        }
        List<SObject> results = Database.query(q);
        return results;
    }

    /**
     * Formats input String to return Date
     *
     * @param unformatedDate (String) date in format dd/MM/yyyy
     *
     * @return (Date) from input String
     */
    public static Date formatDate(String unformatedDate) {
        String[] d = unformatedDate.split('/');
        Date newDate = Date.today();
        if (d.size() <> 3) {
            return newDate;
        }
        try {
            newDate = Date.newInstance(Integer.valueOf(d[2]), Integer.valueOf(d[1]), Integer.valueOf(d[0]));
        } catch (TypeException e) {
            System.debug('Error parsing date from view : ' + unformatedDate);
        }
        return newDate;
    }
}